# This is a basic workflow to help you get started with Actions

name: build-and-test

permissions:
  id-token: write
  contents: read
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Checking compilation errors while generating image
        run: env GOOS=linux go build -o "sumologic-extension" "lambda-extensions/sumologic-extension.go"

      - name: Configure AWS credentials via OIDC and IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::285573938264:role/LambdaExtensionPublishRole
          aws-region: us-east-1

      - name: Run Unit Tests
        env:
          AWS_REGION: us-east-1
        run: go test  ./...
